In [11]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [12]:
import numpy as np
list1=[1,2,3]
a=np.array(list1)
print(a)

[1 2 3]


In [13]:
import numpy as np
list1=[1,2,3]
a=np.array(list1)
print(type(a))

<class 'numpy.ndarray'>


In [22]:
import numpy as np
a=np.array([42])
print(a)

[42]


In [23]:
import numpy as np
a=np.array([[42,2,3],[23,3,4]])
print(a)

[[42  2  3]
 [23  3  4]]


In [24]:
import numpy as np
a=np.array([[42,2,3],[23,3,4],[23,3,4]])
print(a)

[[42  2  3]
 [23  3  4]
 [23  3  4]]


In [51]:
import numpy as np
a=np.array([[[42,2,3],[23,3,4],[23,3,4]]])
b=np.array([[42,2,3],[23,3,4]])
c=np.array([42])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(a[0,2,2])
print(a[0,2,2])
print(a[0,2,2]+a[0,2,0]+a[0,1,2])

3
2
1
4
4
31


In [30]:
import numpy as np
a=np.array([1,2,3])
print(a[0]+a[1])

3
